include:
  - path: backend/docker-compose.yml

services:
  proxy:
    image: nginx:1.13.6-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./:/usr/share/nginx/html
